apiVersion: apps/v1
kind: Deployment
metadata:
  name: kubia
  labels:
    app: kubia
spec:
  replicas: 2
  minReadySeconds: 10
  selector:
    matchLabels:
      app: kubia
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
    type: RollingUpdate
  template:
    metadata:
      name: kubia
      labels:
        app: kubia
    spec:
      containers:
      - image: abcxlab/kubia
        name: kubia 
        ports:
          - containerPort: 8080
        resources:
          requests:
            memory: 100Mi
            cpu: 200m
          limits:
            cpu: 400m
            memory: 200Mi
        readinessProbe:
          periodSeconds: 1
          httpGet:
            path: /
            port: 8080
          initialDelaySeconds: 5
        livenessProbe:
          periodSeconds: 3
          timeoutSeconds: 1
          httpGet:
            path: /
            port: 8080
          initialDelaySeconds: 5

