apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: kubeapps
  namespace: kubeapps
spec:
  rules:
  - host: apps.abcxlab.com
    http:
      paths:
      - path: /
        backend:
          serviceName: kubeapps
          servicePort: 80
